name: Build apk & notify

on:
  push:
    branches:
      - draft

jobs:
  build:
    name: Build apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build apk

      - uses: actions/upload-artifact@v2
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk

  notify-telegram:
    name: Send telegram notification w/ pr url
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download built apk from artifacts provider
        uses: actions/download-artifact@v2
        with:
          name: apk

      - name: send custom message with args
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_BOT_CHAT }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "#frontend\n\nNew apk build"
          document: app-release.apk

  notify-matrix:
    name: Send matrix notification w/ built apk
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download built apk from artifacts provider
        uses: actions/download-artifact@v2
        with:
          name: apk
      - name: send apk to matrix
        uses: better-notes/send-matrix-file@v1
        with:
          file-path: app-release.apk
          content-type: application/vnd.android.package-archive
          file-name: app-release.apk
          file-type: m.file
          chat-id: ${{ secrets.MATRIX_CHAT_ID }}
          authentication-token: ${{ secrets.MATRIX_TOKEN }}
