name: Notify pull requests.

on:
  - pull_request

jobs:
  notify-telegram:
    name: Send telegram notification w/ pr url
    runs-on: ubuntu-latest
    steps:
      - name: send custom message with args
        uses: appleboy/telegram-action@master
        env:
          PR_NUMBER: ${{ github.event.number }}
        with:
          to: ${{ secrets.TELEGRAM_BOT_CHAT }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "#frontend\n\nCheck out pull request - https://github.com/better-notes/android-client/pull/${{ env.PR_NUMBER }}"
          disable_web_page_preview: true

  notify-matrix:
    name: Send matrix notification w/ pr url
    runs-on: ubuntu-latest
    steps:
      - name: Send message to test channel
        uses: better-notes/send-matrix-message@v1
        with:
          message: |
            # frontend

            Check out pull request - https://github.com/better-notes/android-client/pull/${{ github.event.number }}
          chat-id: ${{ secrets.MATRIX_CHAT_ID }}
          authentication-token: ${{ secrets.MATRIX_TOKEN }}
